In [8]:
import torch
from torch.autograd import Variable

torch.manual_seed(777)

x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5],
          [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0],
          [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

X = Variable(torch.Tensor(x_data))
Y = Variable(torch.Tensor(y_data))
nb_classes = 3

# softmax = exp(logits) / reduce_sum(exp(logits), dim)
softmax = torch.nn.Softmax()
linear = torch.nn.Linear(4, nb_classes, bias = True)
model = torch.nn.Sequential(linear, softmax)

optimizer = torch.optim.SGD(model.parameters(), lr = 0.1)

for step in range(2001):
    optimizer.zero_grad()
    hypothesis = model(X)
    
    # cost / loss = Cross - Entropy
    cost = -Y * torch.log(hypothesis)
    cost = torch.sum(cost, 1).mean()
    cost.backward()
    optimizer.step()
    
    if step % 200 == 0:
        print("step :", step, "\tcost :", cost.data.numpy())
        
# Testing & One-hot encoding
print("------------------------------")
a = model(Variable(torch.Tensor([[1, 11, 7, 9]])))
print(a.data.numpy(), torch.max(a, 1)[1].data.numpy())

print("------------------------------")
b = model(Variable(torch.Tensor([[1, 3, 4, 3]])))
print(b.data.numpy(), torch.max(b, 1)[1].data.numpy())

print("------------------------------")
c = model(Variable(torch.Tensor([[1, 1, 0, 1]])))
print(c.data.numpy(), torch.max(c, 1)[1].data.numpy())

print("------------------------------")
all = model(Variable(torch.Tensor([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]])))
print(all.data.numpy(), torch.max(all, 1)[1].data.numpy())

C:\Users\sonwo\Anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\container.py:92: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


step : 0 	cost : 2.3687892
step : 200 	cost : 0.54633194
step : 400 	cost : 0.45158795
step : 600 	cost : 0.37642643
step : 800 	cost : 0.3045038
step : 1000 	cost : 0.24127787
step : 1200 	cost : 0.2179132
step : 1400 	cost : 0.19881801
step : 1600 	cost : 0.18269488
step : 1800 	cost : 0.16890591
step : 2000 	cost : 0.15698561
------------------------------
[[7.6587372e-03 9.9233150e-01 9.6463118e-06]] [1]
------------------------------
[[0.82809925 0.15501602 0.01688479]] [0]
------------------------------
[[1.3566345e-08 3.5339090e-04 9.9964654e-01]] [2]
------------------------------
[[7.6587442e-03 9.9233150e-01 9.6463118e-06]
 [8.2809913e-01 1.5501603e-01 1.6884783e-02]
 [1.3566319e-08 3.5339055e-04 9.9964654e-01]] [1 0 2]
