In [6]:
import numpy as np

# 1. 배열 만들기
b = np.array([2, 4, 6, 8])
b

array([2, 4, 6, 8])

In [8]:
b.ndim # 차원

1

In [9]:
b.size # 갯수

4

In [10]:
b.shape # 배열 형태

(4,)

In [11]:
# 2. 배열 만들기
# arange() : range()와 비슷하다.
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a.ndim

1

In [14]:
a.shape

(10,)

In [15]:
a.size

10

In [17]:
# if) 인자를 두 개로
a = np.arange(7, 11)
a

array([ 7,  8,  9, 10])

In [21]:
# 세 번째 인자로 step 크기를 지정할 수 있다.
a = np.arange(7, 12, 2)
a

array([ 7,  9, 11])

In [23]:
# 부동 소수점도 가능하다.
f = np.arange(2.0, 9.8, 0.4)
f

array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6, 6. , 6.4, 6.8,
       7.2, 7.6, 8. , 8.4, 8.8, 9.2, 9.6])

In [24]:
# dtype을 통해 생성할 배열의 타입을 정할 수 있다.
g = np.arange(10, 4, -1.5, dtype = np.float)
g

array([10. ,  8.5,  7. ,  5.5])

In [25]:
# 3. 배열 만들기
# 1) zeroes() : 모든 값이 0인 배열을 반환한다.
a = np.zeros([3, ])
a

array([0., 0., 0.])

In [26]:
a.ndim

1

In [27]:
a.shape

(3,)

In [28]:
a.size

3

In [29]:
# zeros를 이용한 2차원 배열
b = np.zeros([2, 4])
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
b.ndim

2

In [33]:
b.shape

(2, 4)

In [34]:
b.size

8

In [35]:
# 2) ones() : 같은 값으로 배열을 채운다.
k = np.ones((3, 5))
k

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
# 3) random() : 0과 1사이의 랜덤 값으로 배열을 생성한다.
m = np.random.random((3, 5))
m

array([[0.37745059, 0.29124269, 0.36409074, 0.7322925 , 0.73476608],
       [0.59799605, 0.82777176, 0.36477841, 0.1795083 , 0.76212754],
       [0.73831757, 0.95118777, 0.27110614, 0.71218169, 0.02549433]])

In [40]:
# 4. 배열 모양 바꾸기
# reshape()
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a = a.reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
a.ndim

2

In [43]:
a.shape

(2, 5)

In [44]:
a.size

10

In [45]:
a = a.reshape(5, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [46]:
a.ndim

2

In [47]:
a.shape

(5, 2)

In [48]:
a.size

10

In [50]:
# 투플 값을 할당해서 모양을 바꿀 수 있다.
a.shape = (2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [52]:
# 5. 항목 얻기
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a[7]

7

In [54]:
a[-1]

9

In [55]:
# 2차원 이상일 경우 ','로 구분
a.shape = (2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
a[1, 2]

7

In [57]:
# 슬라이스는 대괄호([]) 안에서만 작동한다.
a = np.arange(10)
a = a.reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
a[0, 2 : ]

array([2, 3, 4])

In [59]:
a[-1, : 3]

array([5, 6, 7])

In [60]:
a[ : , 2 : 4] = 1000
a

array([[   0,    1, 1000, 1000,    4],
       [   5,    6, 1000, 1000,    9]])

In [66]:
# 6. 배열 연산
from numpy import *
a = arange(4)
a

array([0, 1, 2, 3])

In [67]:
a *= 3
a

array([0, 3, 6, 9])

In [68]:
# 보통 파이썬 리스트에서 각 배열의 항목을 곱하려면 반복문이나 리스트 컴프리핸션을 사용해야 한다.
plain_list = list(range(4))
plain_list

[0, 1, 2, 3]

In [69]:
plain_list = [num * 3 for num in plain_list]
plain_list

[0, 3, 6, 9]

In [70]:
# 다른 함수에도 적용이 된다.
a = zeros((2, 5)) + 17
a

array([[17., 17., 17., 17., 17.],
       [17., 17., 17., 17., 17.]])

In [71]:
# @를 이용하여 행렬 곱
a = np.array([[1, 2], [3, 4]])
b = a @ a
b

array([[ 7, 10],
       [15, 22]])